### ISSUE TITLE
does org-notify remove from org-contrib?

### ISSUE THREAD

**Issue by wztdream** [p-m/org-notify#6]
Hi,
`org-notify` is great, I use it a lot. But I just found `org-notify` package missing, it seems this package were in `org-contrib`, but now it seems it is removed? And neither can I find it in melpa, so what is the status of this package? Will it keep alive in the long run?

**Comment by p-m** [comment]
On Fri, Jul 29 2022, wztdream wrote:

> what is the status of this package?

Hi,

It is in GNU ELPA: https://elpa.gnu.org/packages/org-notify.html


> Will it keep alive in the long run?

Yes, I try to do that.

Cheers, Peter

**Comment by p-m** [comment]
On Fri, Jul 29 2022, wztdream wrote:

> what is the status of this package?

Hi,

It is in ELPA: https://elpa.gnu.org/packages/org-notify.html


> Will it keep alive in the long run?

Yes, I'll do that!!

Cheers,
-- 
           Peter
